// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Enriqueta, Roboto } from "next/font/google";
const enriqueta = Enriqueta({
  variable: "--font-enriqueta",
  subsets: ["latin"],
  weight:"500"
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight:"400"
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${enriqueta.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
